export const metadata={alternates:{canonical:'/privacidad'},title:'Política de privacidad | Demeter Corp',description:'Cómo trata Demeter Corp los datos personales recogidos en demetercorp.es: responsable, finalidades, base jurídica, conservación y derechos.'}
export default function Privacidad(){return <main className="legal-page"><div className="shell prose"><span className="eyebrow">PROTECCIÓN DE DATOS</span><h1>Política de Privacidad</h1>
<p><strong>Responsable:</strong> DEMETER CORP, S.L. · NIF B21885033 · C/ Boticelli, 1, 21450 Cartaya (Huelva), España.</p>
<h2>Datos que recogemos</h2><p>A través del formulario de contacto podemos recoger nombre y apellidos, empresa, correo electrónico, motivo de contacto y el contenido del mensaje. No solicitamos datos especialmente protegidos mediante este formulario.</p>
<h2>Finalidades</h2><p>Los datos se utilizan para atender consultas, estudiar propuestas de activos, proyectos u oportunidades de inversión, gestionar relaciones comerciales o profesionales y mantener las comunicaciones necesarias derivadas de la solicitud.</p>
<h2>Base jurídica</h2><p>El tratamiento se basa principalmente en el consentimiento del interesado al enviar el formulario y, cuando exista una relación o negociación empresarial, en la aplicación de medidas precontractuales o en el interés legítimo de gestionar la relación profesional, según corresponda.</p>
<h2>Conservación</h2><p>Los datos se conservarán durante el tiempo necesario para atender la solicitud y, posteriormente, durante los plazos exigidos por las obligaciones legales o por la defensa de posibles responsabilidades.</p>
<h2>Destinatarios y proveedores</h2><p>No vendemos datos personales. Los datos podrán ser tratados por proveedores tecnológicos que prestan servicios a la web o al correo electrónico bajo las garantías contractuales aplicables. El formulario utiliza un proveedor de entrega de correo configurado por Demeter Corp.</p>
<h2>Derechos</h2><p>Puede ejercer los derechos de acceso, rectificación, supresión, oposición, limitación y portabilidad, así como retirar el consentimiento cuando proceda, mediante una solicitud enviada a través del formulario de Contacto, indicando que se trata de una solicitud de protección de datos y aportando la información necesaria para verificar su identidad.</p><p>También puede presentar una reclamación ante la Agencia Española de Protección de Datos si considera que el tratamiento no se ajusta a la normativa.</p>
<h2>Seguridad</h2><p>Demeter Corp aplica medidas técnicas y organizativas razonables para proteger los datos frente a accesos no autorizados, pérdida, alteración o divulgación.</p>
<p className="legal-note">Texto adaptado al formulario de contacto previsto para demetercorp.es. Debe revisarse si se incorporan analítica, newsletter, área privada de inversores, CRM u otros tratamientos.</p></div></main>}
