export const metadata={alternates:{canonical:'/sectores'},title:'Agua, energía, infraestructura y patrimonio | Grupo Demeter',description:'Grupo Demeter opera en agua y reutilización, energía y transición energética, infraestructura y licitación pública, patrimonio inmobiliario y desarrollo tecnológico propio.'}

const sectores=[
 {id:'agua',name:'AGUA',parrafos:[
  'El agua ha dejado de ser un recurso que se da por hecho. La combinación de estrés hídrico estructural, marcos regulatorios cada vez más exigentes y una demanda creciente por parte de la agricultura, la industria y el turismo ha convertido la gestión del agua no destinada a consumo humano en uno de los sectores con mayor necesidad de inversión y capacidad técnica de los próximos años. La reutilización de aguas regeneradas, en particular, ha pasado de ser una alternativa marginal a una exigencia de planificación hídrica en buena parte del territorio español, especialmente en el sur peninsular.',
  'La oportunidad está precisamente en esa transición regulatoria. El Reglamento (UE) 2020/741 y su desarrollo mediante el Real Decreto 1085/2024 —que sustituye al derogado Real Decreto 1620/2007— han establecido un marco más exigente y más claro a la vez, que favorece a quienes lo dominan técnica y administrativamente. Administraciones, comunidades de regantes, industrias y propietarios de suelo agrícola necesitan cada vez más un interlocutor capaz de moverse con solvencia entre la ingeniería del tratamiento, el procedimiento administrativo de la concesión y la viabilidad económica del conjunto.',
  'Demeter Water Consulting opera exactamente en esa intersección. Analiza la viabilidad técnica y normativa de proyectos de regeneración y reutilización, diseña la infraestructura hidráulica asociada, y acompaña la tramitación de concesiones administrativas de principio a fin. Su trabajo cubre también proyectos de infraestructura de regadío, donde la gestión eficiente del recurso condiciona directamente la rentabilidad de la actividad agrícola.',
  'El socio que buscamos en este sector es quien dispone del activo —suelo, instalación industrial, concesión existente, necesidad de recurso hídrico— pero no de la capacidad técnica y normativa para desarrollarlo: administraciones locales, comunidades de regantes, industrias con necesidades de reutilización y propietarios de explotaciones agrícolas de escala relevante.',
 ]},
 {id:'energia',name:'ENERGÍA',parrafos:[
  'El sector energético español atraviesa una transición que va más allá de la sustitución de fuentes convencionales por renovables. La maduración del marco regulatorio, la necesidad de almacenamiento y gestión de la intermitencia, y la aparición de vectores energéticos como el hidrógeno verde están redefiniendo qué significa desarrollar un proyecto energético viable a medio plazo.',
  'La oportunidad no está únicamente en la generación. Está en la capacidad de estructurar proyectos que combinen generación, almacenamiento y, en algunos casos, transformación —como el hidrógeno verde— con una lectura correcta de la evolución regulatoria y de mercado. Los proyectos que se limitan a replicar el modelo de generación convencional compiten en un mercado cada vez más estrecho de márgenes; los que incorporan una visión de transición energética real acceden a un espacio con menos competencia y mayor recorrido.',
  'Demeter Soluciones Estratégicas desarrolla y ejecuta proyectos energéticos con esa doble perspectiva: capacidad de ejecución sobre proyectos convencionales de generación, y capacidad de análisis y estructuración sobre iniciativas de mayor complejidad tecnológica, incluido el hidrógeno verde como vector de futuro. Su integración con el resto del grupo permite además evaluar el encaje de un proyecto energético con necesidades de infraestructura o de patrimonio existentes en una misma operación.',
  'Buscamos como socios en este sector a propietarios de suelo o de infraestructura con potencial energético, promotores que necesiten un ejecutor técnico solvente, y administraciones o industrias interesadas en proyectos de generación o de transición energética.',
 ]},
 {id:'infraestructura',name:'INFRAESTRUCTURA',parrafos:[
  'La infraestructura pública en España —hidráulica, energética, de movilidad, de servicios— tiene una necesidad de renovación y de mantenimiento que no siempre encuentra en el mercado privado contratistas capaces de combinar la solvencia técnica con la comprensión precisa del procedimiento de contratación pública. La licitación pública no es solo un mecanismo de acceso a contratos: es un procedimiento administrativo con reglas propias, donde el error de forma puede invalidar la mejor propuesta técnica.',
  'La oportunidad está en esa combinación poco frecuente: capacidad de ejecución técnica real —no solo comercial— junto con el conocimiento administrativo necesario para concurrir correctamente a un procedimiento de contratación pública, y para ejecutar el contrato adjudicado con la disciplina que la administración exige en materia de plazos, calidad y justificación documental.',
  'Demeter Soluciones Estratégicas concurre y ejecuta contratos de infraestructura y de gestión de servicios vinculados, apoyándose cuando el proyecto lo requiere en la capacidad técnica de Demeter Water Consulting en materia hídrica o en la experiencia patrimonial de Demeter God cuando el contrato involucra activos inmobiliarios o de gestión de instalaciones.',
  'El socio natural en este sector son las administraciones públicas que licitan estos contratos, y también empresas privadas o consorcios que buscan un ejecutor técnico solvente para operaciones de infraestructura de cierta complejidad.',
 ]},
 {id:'patrimonio',name:'PATRIMONIO E INMOBILIARIO',parrafos:[
  'El mercado inmobiliario español, y en particular el andaluz, combina zonas de fuerte presión de demanda —especialmente en el segmento turístico y residencial de costa— con un parque de activos que en muchos casos requiere una rehabilitación seria antes de generar el valor que su ubicación permitiría. Comprar bien, en este contexto, no es solo una cuestión de precio de adquisición: es una cuestión de capacidad técnica para transformar el activo y de disciplina para operarlo después con criterio de largo plazo.',
  'La oportunidad está en los activos que exigen ese trabajo intermedio: edificios o suelos con potencial evidente pero con una situación técnica, urbanística o de estado de conservación que aleja al comprador puramente financiero. Quien es capaz de evaluar correctamente ese potencial, ejecutar la transformación necesaria y, sobre todo, operar el activo después de la inversión inicial, accede a un margen y a un tipo de activo que el mercado más generalista no persigue con la misma profundidad.',
  'Demeter God cubre precisamente ese ciclo completo: adquisición, desarrollo o rehabilitación integral, y explotación directa, con particular presencia en alojamiento turístico de gestión propia. Esa continuidad —el mismo equipo que compra, transforma y opera— es la que permite tomar mejores decisiones de adquisición.',
  'Buscamos como socios en este sector a propietarios de activos con necesidad de reposicionamiento, e inversores interesados en patrimonio inmobiliario y turístico con vocación de permanencia, no de rotación especulativa de corto plazo.',
 ]},
 {id:'tecnologia',name:'TECNOLOGÍA Y DATOS',parrafos:[
  'La toma de decisiones de inversión y de gestión de activos reales —agua, energía, infraestructura, inmuebles— depende de información dispersa, procedente de fuentes técnicas, normativas y de mercado que rara vez están integradas en un mismo flujo de trabajo. La mayoría de los actores de estos sectores siguen tomando decisiones con herramientas genéricas que no reflejan la realidad técnica de un activo real.',
  'La oportunidad está en desarrollar herramientas propias, ajustadas exactamente al tipo de análisis que un grupo diversificado en activos reales necesita: viabilidad técnica y normativa, modelización económica de proyectos con horizontes largos, y seguimiento del desempeño de activos ya en explotación.',
  'Demeter Soluciones Estratégicas desarrolla y mantiene el software propio que el grupo utiliza de forma transversal para el análisis de oportunidades de inversión y la gestión del desempeño de sus activos. Este desarrollo tecnológico interno mejora directamente la calidad de las decisiones de originación, estructuración y gestión del resto de sociedades del grupo, y en determinados casos puede convertirse en un activo o servicio ofrecido a terceros.',
  'El interés en este sector es doble: como capacidad interna que refuerza la ejecución del resto del grupo, y como línea de desarrollo tecnológico propio con potencial comercial independiente para socios interesados en analítica aplicada a activos reales.',
 ]},
]

import HeroArt from '../../components/HeroArt'

export default function Sectores(){return <>
 <section className="page-hero"><div className="shell page-hero-grid"><div><span className="eyebrow">SECTORES</span><h1>Cinco sectores. Un mismo criterio: activos reales, regulación exigente, ejecución propia.</h1></div><div className="page-hero-art"><HeroArt kind="wave" accent="#089dd8"/></div></div></section>
 <section className="section white"><div className="shell">{sectores.map(s=><div className="sector-block" id={s.id} key={s.id}><span className="eyebrow">{s.name}</span>{s.parrafos.map((p,i)=><p key={i}>{p}</p>)}</div>)}</div></section>
 <section className="section dark"><div className="shell" style={{textAlign:'center'}}><h2 style={{color:'white'}}>Cinco sectores, una misma capacidad de ejecución.</h2><div className="actions" style={{justifyContent:'center'}}><a className="btn primary" href="/inversores#dossier">Solicitar acceso al dossier</a><a className="btn outline-dark" href="/contacto" style={{borderColor:'rgba(255,255,255,.35)',color:'white'}}>Plantear un proyecto</a></div></div></section>
</>}
