export const metadata={title:'Aviso legal | Demeter Corp'}
export default function AvisoLegal(){return <main className="legal-page"><div className="shell prose"><span className="eyebrow">INFORMACIÓN LEGAL</span><h1>Aviso legal</h1>
<p>En cumplimiento de la legislación vigente, se informa al usuario de que la entidad responsable de este sitio web es <strong>DEMETER CORP, S.L.</strong>, con NIF <strong>B21885033</strong>, domicilio social en <strong>C/ Boticelli, 1, 21450 Cartaya (Huelva), España</strong>, e inscrita en el Registro Mercantil de Huelva, Sección 8, Hoja H-29749, Inscripción 1.</p>
<p>Las comunicaciones relacionadas con esta web y con protección de datos podrán realizarse mediante el formulario disponible en la página de Contacto.</p>
<h2>Condición de usuario</h2><p>El acceso y uso de esta web atribuye la condición de usuario e implica la aceptación de las disposiciones de este aviso legal en la versión publicada en cada momento.</p>
<h2>Responsabilidad del usuario</h2><p>El acceso, navegación y utilización de los contenidos se realizan bajo responsabilidad del usuario, que se compromete a hacer un uso lícito, razonable y de buena fe, respetando la legislación aplicable, el orden público y los derechos de Demeter Corp y de terceros.</p>
<h2>Descargo y limitación de responsabilidad</h2><p>Los contenidos tienen carácter informativo y pueden contener errores, omisiones o información sujeta a cambios. Demeter Corp podrá modificar o actualizar la web en cualquier momento y no garantiza la ausencia absoluta de interrupciones, incidencias técnicas o elementos dañinos, aunque adopta medidas razonables para evitarlos.</p><p>La información publicada no constituye por sí sola una oferta vinculante, recomendación de inversión ni asesoramiento financiero, jurídico, fiscal o técnico. Cualquier decisión deberá basarse en la documentación contractual y técnica correspondiente y, cuando proceda, en asesoramiento profesional independiente.</p>
<h2>Enlaces y contenido de terceros</h2><p>Esta web puede enlazar a sitios gestionados por terceros, incluida la web independiente de Demeter God. Demeter Corp no controla ni responde de sus contenidos, disponibilidad o políticas.</p>
<h2>Propiedad intelectual e industrial</h2><p>Los textos, identidad visual, diseños, logotipos, imágenes y demás contenidos de esta web pertenecen a Demeter Corp, a sociedades de su grupo o a terceros licenciantes. Queda prohibida su reproducción, distribución, comunicación pública o transformación sin autorización previa cuando resulte exigible.</p>
<h2>Legislación aplicable</h2><p>Este sitio se rige por la legislación española. Las controversias se someterán a los juzgados y tribunales que resulten competentes conforme a la normativa aplicable.</p>
<p className="legal-note">Versión web preparada para demetercorp.es. Conviene que el texto definitivo sea revisado por el asesor jurídico de la sociedad antes de publicación.</p></div></main>}
