export const metadata={title:'Proyectos — Grupo Demeter',description:'Selección anonimizada de proyectos de Grupo Demeter en agua, energía, infraestructura y patrimonio. Detalle disponible bajo acuerdo de confidencialidad.'}

const proyectos=[
 ['AGUA','Planta de regeneración de aguas para reutilización agrícola','Andalucía Occidental','Promotor y gestor de la tramitación','En tramitación','Proyecto de regeneración de aguas residuales tratadas para su reutilización en riego agrícola, en una zona con presión creciente sobre el recurso hídrico convencional. Demeter Water Consulting ha desarrollado el análisis técnico y normativo de viabilidad y acompaña actualmente la tramitación de la concesión administrativa correspondiente, conforme al Reglamento (UE) 2020/741 y al Real Decreto 1085/2024.'],
 ['ENERGÍA','Estudio de viabilidad para producción de hidrógeno verde','Suroeste peninsular','Analista y estructurador','En estudio','Análisis de viabilidad técnica y económica para el desarrollo de una planta de producción de hidrógeno verde asociada a capacidad de generación renovable existente en la zona. Demeter Soluciones Estratégicas ha evaluado el marco regulatorio aplicable, las alternativas tecnológicas de electrólisis y los posibles usos industriales del hidrógeno producido.'],
 ['PATRIMONIO','Rehabilitación integral de edificio para uso mixto residencial y turístico','Costa de Huelva','Promotor y gestor de la explotación','En ejecución','Rehabilitación integral de un edificio existente para destinarlo a uso mixto, combinando unidades residenciales y alojamiento turístico de gestión directa. Demeter God ha asumido el proyecto desde la adquisición hasta la dirección de la obra, y gestionará directamente la explotación turística una vez finalizada la rehabilitación.'],
 ['INFRAESTRUCTURA','Licitación pública para gestión de infraestructura hidráulica','Andalucía','Licitador y ejecutor','En tramitación','Concurrencia a un procedimiento de licitación pública para la gestión y mantenimiento de infraestructura hidráulica de titularidad administrativa. Demeter Soluciones Estratégicas, con el apoyo técnico de Demeter Water Consulting, ha preparado la oferta técnica y económica conforme a los pliegos correspondientes.'],
 ['AGUA','Proyecto de reutilización de aguas industriales','Andalucía Oriental','Consultor técnico y normativo','En estudio','Estudio de viabilidad para la reutilización de aguas de proceso en una instalación industrial, con el objetivo de reducir la dependencia de recursos hídricos convencionales. Demeter Water Consulting ha analizado las alternativas de tratamiento disponibles y el encaje normativo de la operación.'],
 ['PATRIMONIO','Adquisición y reposicionamiento de suelo urbano','Andalucía','Inversor y promotor','En estudio','Análisis de viabilidad para la adquisición de suelo urbano con potencial de reposicionamiento, en una ubicación con dinámica de desarrollo activa. Demeter God ha evaluado el encaje urbanístico y la viabilidad económica de distintos usos posibles, dentro de su estrategia de crecimiento patrimonial de largo plazo.'],
 ['TECNOLOGÍA','Desarrollo de herramienta propia de análisis de inversión','Interno / grupo','Desarrollador','En explotación','Herramienta de software desarrollada internamente para sistematizar el análisis de oportunidades de inversión del grupo: viabilidad técnica, normativa, económica y de riesgos en un mismo flujo de trabajo. Se utiliza de forma transversal en la originación y estructuración de operaciones de todas las sociedades del grupo.'],
 ['INFRAESTRUCTURA','Estudio de infraestructura de regadío para explotación agrícola','Andalucía Occidental','Consultor técnico','En estudio','Análisis de una infraestructura de regadío para una explotación agrícola de escala relevante, incluyendo el estudio de disponibilidad del recurso, alternativas de captación y eficiencia de distribución.'],
 ['PATRIMONIO','Gestión de cartera de alojamiento turístico','Andalucía','Gestor de la explotación','En explotación','Gestión directa de una cartera de unidades de alojamiento turístico, con foco en la optimización de la ocupación, la experiencia del huésped y el mantenimiento del valor del activo en el tiempo.'],
]

import HeroArt from '../../components/HeroArt'

export default function Proyectos(){return <>
 <section className="page-hero"><div className="shell page-hero-grid"><div><span className="eyebrow">PROYECTOS</span><h1>Lo suficiente para entender la capacidad; no lo bastante para identificar la operación.</h1><p>Cada ficha se presenta de forma anonimizada. El detalle completo —cifras, contraparte, calendario, documentación— se comparte exclusivamente en sala, bajo acuerdo de confidencialidad. Lo que no está en esta página es exactamente lo que se habla en la primera reunión.</p></div><div className="page-hero-art"><HeroArt kind="layers" accent="#c7a25b"/></div></div></section>
 <section className="section white"><div className="shell"><div className="project-grid">{proyectos.map((p,i)=><article className="project" key={i}><span className="project-meta">{p[0]} · {p[2]}</span><h3>{p[1]}</h3><p style={{fontSize:13,color:'var(--steel)',fontWeight:700,margin:'0 0 14px'}}>{p[3]} · {p[4]}</p><p>{p[5]}</p><span className="confidential-badge">Detalle disponible bajo acuerdo de confidencialidad</span></article>)}</div></div></section>
 <section className="section dark"><div className="shell" style={{textAlign:'center'}}><h2 style={{color:'white'}}>Una muestra deliberadamente limitada.</h2><p className="lead" style={{color:'#cad6df',margin:'0 auto 30px'}}>Si necesita valorar la capacidad de ejecución de Demeter con más profundidad —cifras, contrapartes, documentación—, ese es exactamente el contenido del dossier de inversores.</p><div className="actions" style={{justifyContent:'center'}}><a className="btn primary" href="/inversores#dossier">Solicitar acceso al dossier</a></div></div></section>
</>}
