import Link from 'next/link'

export default function Home(){
 const companies=[
  {name:'Demeter Corp',tag:'La cabecera del grupo.',txt:'Gobierno corporativo, estrategia y asignación de capital entre las sociedades operativas. Define el criterio de inversión y responde por el conjunto del grupo ante inversores y contrapartes institucionales.',img:'/logos/demeter-corp.png',href:'/empresas#demeter-corp'},
  {name:'Demeter God',tag:'El brazo patrimonial.',txt:'Adquisición, desarrollo, rehabilitación y explotación de activos inmobiliarios, incluido el alojamiento turístico de gestión directa. Convierte activos con potencial en patrimonio que genera valor de forma sostenida.',img:'/logos/demeter-god.png',href:'https://demetergod.com',external:true},
  {name:'Demeter Water Consulting',tag:'La consultoría del agua.',txt:'Regeneración y reutilización de aguas, infraestructura hidráulica y tramitación de concesiones administrativas. Opera en el marco normativo europeo y español más exigente en materia de recursos hídricos.',img:'/logos/demeter-water.png',href:'/empresas#demeter-water-consulting'},
  {name:'Demeter Soluciones Estratégicas',tag:'Los grandes contratos.',txt:'Energía, infraestructura, licitación pública y desarrollo tecnológico propio. Asume operaciones de mayor escala y complejidad administrativa, allí donde la ejecución técnica marca la diferencia.',img:'/logos/demeter-soluciones.png',href:'/empresas#demeter-soluciones-estrategicas'},
 ]
 const verticals=[['◉','Agua','De un recurso escaso a un activo gestionado. Regeneración, reutilización y concesiones administrativas bajo el marco normativo vigente.'],['☀','Energía','De la generación convencional al hidrógeno verde. Proyectos energéticos con visión de transición, no solo de rentabilidad inmediata.'],['▥','Infraestructura','Licitación pública y ejecución técnica. Donde la administración necesita un contratista que entienda tanto el pliego como la obra.'],['◇','Patrimonio','Activos inmobiliarios con recorrido. Adquisición, rehabilitación y explotación, con horizonte de largo plazo.'],['◒','Tecnología','Software propio al servicio de la operación. Herramientas desarrolladas internamente para analizar, gestionar y decidir mejor.']]
 const steps=[['01','Originación','Identificamos oportunidades a través de relaciones directas con propietarios de activos, administraciones y operadores del sector, no de intermediación masiva. La mayoría de las operaciones que estudiamos no llegan a un portal público: llegan primero a Demeter.'],['02','Análisis','Antes de comprometer capital o reputación, sometemos cada oportunidad a un análisis técnico, económico, normativo y de riesgos. El objetivo no es descartar rápido, sino entender de verdad qué se está comprando o a qué se está optando.'],['03','Estructuración','Definimos la sociedad vehículo, el reparto de riesgos y el papel de cada parte —Demeter, coinversores, entidades financieras— antes de firmar nada. Una estructuración correcta evita la mayoría de los problemas que aparecen después.'],['04','Ejecución y gestión','No delegamos la ejecución en terceros que no controlamos. Los equipos técnicos de cada sociedad del grupo gestionan la obra, la tramitación o la operación hasta el resultado, y mantienen el activo bajo seguimiento en el tiempo.']]
 const credibility=[['Multidisciplinar','Ingeniería, derecho administrativo, gestión de activos y desarrollo de software bajo un mismo grupo.'],['Integración vertical','Originación, estructuración, ejecución y gestión patrimonial, sin ceder el control a terceros.'],['Licitación pública','Capacidad acreditada para concurrir y ejecutar contratos con administraciones públicas.'],['Gestión directa','Los activos que adquirimos los operamos nosotros, no los delegamos.']]
 return <>
  <section className="hero"><div className="shell hero-grid">
   <div><span className="eyebrow">GRUPO EMPRESARIAL</span><h1>Capital, técnica<br/><span>y ejecución sobre activos reales.</span></h1><p>Grupo Demeter identifica, estructura y ejecuta oportunidades en agua, energía, infraestructura y patrimonio. Una misma matriz, cuatro sociedades especializadas, un mismo criterio: activos con fundamento, gestionados de principio a fin.</p><div className="actions"><Link className="btn primary" href="/inversores#dossier">Solicitar acceso al dossier</Link><Link className="btn" href="/contacto">Plantear un proyecto</Link></div></div>
   <img className="hero-logo" src="/logos/demeter-corp.png" alt="Demeter Corp"/>
  </div></section>

  <section className="section white"><div className="shell content-grid"><div><span className="eyebrow">QUIÉNES SOMOS</span></div><div className="copy">
   <p>Grupo Demeter nace de una convicción simple: los activos reales —el agua, la energía, el suelo, la infraestructura— no se gestionan bien desde la generalidad. Exigen especialización técnica, capacidad de ejecución y una estructura societaria capaz de asumir el riesgo correcto en cada fase.</p>
   <p>Por eso Demeter no es una sola empresa, sino una matriz que gobierna cuatro sociedades especializadas, cada una con su propio ámbito de actuación, su propio equipo técnico y su propia responsabilidad sobre el resultado. Demeter Corp define la estrategia y asigna el capital. Demeter God adquiere, desarrolla y explota patrimonio. Demeter Water Consulting proyecta y gestiona infraestructura hídrica. Demeter Soluciones Estratégicas ejecuta contratos de energía, infraestructura y tecnología.</p>
   <p>Esta arquitectura no es burocracia: es la manera de operar con rigor en sectores donde el error técnico o regulatorio cuesta caro, y de ofrecer a un inversor o a un socio institucional una contraparte que entiende el activo antes de hablar de él.</p>
  </div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">NUESTRAS EMPRESAS</span></div><div><h2>Cuatro sociedades. Un mismo grupo.</h2><p className="lead">Cada sociedad opera con su propio equipo técnico y su propia responsabilidad sobre el resultado.</p></div></div><div className="company-grid">{companies.map(c=><article className="company-card" key={c.name}><div><img src={c.img} alt={c.name}/><h3>{c.name}</h3><span className="eyebrow">{c.tag}</span><p>{c.txt}</p>{c.external ? <a className="text-link" href={c.href} target="_blank" rel="noopener noreferrer">Leer más →</a> : <Link className="text-link" href={c.href}>Leer más →</Link>}</div></article>)}</div></div></section>

  <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">SECTORES</span></div><div><h2>Cinco verticales, un mismo criterio.</h2></div></div><div className="sector-grid">{verticals.map(v=><div className="sector" key={v[1]}><div className="icon">{v[0]}</div><b>{v[1]}</b><span>{v[2]}</span></div>)}</div></div></section>

  <section className="section white"><div className="shell"><div className="section-head"><div><span className="eyebrow">CÓMO TRABAJAMOS</span></div><div><h2>De la oportunidad al activo gestionado.</h2></div></div></div></section>
  <section className="section dark" style={{paddingTop:0}}><div className="shell"><div className="steps-grid">{steps.map(s=><div className="step" key={s[0]}><strong>{s[0]} · {s[1]}</strong><p>{s[2]}</p></div>)}</div></div></section>

  <section className="section white"><div className="shell"><div className="section-head"><div><span className="eyebrow">CAPACIDAD</span></div><div><h2>Lo que sostiene cada operación.</h2></div></div><div className="values cols-4">{credibility.map(c=><div className="value" key={c[0]}><h3>{c[0]}</h3><p>{c[1]}</p></div>)}</div></div></section>

  <section className="section dark"><div className="shell content-grid"><div><span className="eyebrow">PARA INVERSORES</span></div><div className="copy">
   <h2 style={{color:'white'}}>Exposición a activos reales, sin ceder el control.</h2>
   <p style={{color:'#cad6df'}}>Grupo Demeter trabaja con inversores que buscan exposición a activos reales —agua, energía, infraestructura, patrimonio— sin renunciar al control sobre cómo se ejecuta cada operación. No ofrecemos un producto financiero estandarizado: estructuramos cada entrada de capital en torno a un activo o una cartera concretos, con la sociedad vehículo, la gobernanza y el reporting que corresponda a cada caso.</p>
   <p style={{color:'#cad6df'}}>La información pública de este sitio es deliberadamente limitada. El detalle de cada operación —cifras, contrapartes, calendario— se comparte en sala, bajo acuerdo de confidencialidad, con quien acredita interés real. Si busca esa conversación, el primer paso es simple.</p>
   <div className="actions"><Link className="btn primary" href="/inversores#dossier">Solicitar acceso al dossier</Link></div>
  </div></div></section>

  <section className="section white"><div className="shell" style={{textAlign:'center'}}><span className="eyebrow">DOS FORMAS DE TRABAJAR CON NOSOTROS</span><h2>Coloque capital, o plantee un proyecto.</h2><p className="lead" style={{margin:'0 auto 30px'}}>Si busca colocar capital en activos reales con ejecución propia, solicite acceso al dossier de inversores. Si representa una administración, una empresa o un propietario de activos con un proyecto concreto, cuéntenoslo directamente.</p><div className="actions" style={{justifyContent:'center'}}><Link className="btn primary" href="/inversores#dossier">Solicitar acceso al dossier</Link><Link className="btn outline-dark" href="/contacto">Plantear un proyecto</Link></div></div></section>
 </>
}
