import Link from 'next/link'

export default function Home(){
 const companies=[
  {img:'/logos/demeter-god.png',name:'Demeter God',sub:'Luxury Hospitality',txt:'Gestión de apartamentos turísticos de lujo y experiencias de hospitalidad con una visión patrimonial y de largo plazo.',line:'gold',href:'https://demetergod.com',external:true},
  {img:'/logos/demeter-soluciones.png',name:'Demeter Soluciones Estratégicas',sub:'Energy · Agriculture · Strategic Assets',txt:'Intermediación y comercialización de activos de terceros, plantas fotovoltaicas, activos energéticos y fincas agrícolas.',line:'green'},
  {img:'/logos/demeter-water.png',name:'Demeter Water Consulting',sub:'Water Solutions',txt:'Consultoría, ingeniería y gestión de proyectos vinculados al agua no destinada a consumo humano.',line:'blue'}
 ]
 const sectors=[['▥','Activos estratégicos','Oportunidades reales y activos con fundamento.'],['☀','Energía','Proyectos, plantas y transición energética.'],['◒','Agricultura','Fincas, suelo productivo y recursos.'],['◉','Agua','Infraestructura y gestión del recurso.'],['◇','Hospitality','Gestión de activos turísticos premium.']]
 return <>
  <section className="hero"><div className="shell hero-grid">
   <div><span className="eyebrow">GRUPO EMPRESARIAL PRIVADO</span><h1>Activos reales.<br/><span>Visión de largo plazo.</span></h1><p>Demeter Corp es la matriz de un grupo empresarial especializado en activos, recursos naturales, hospitality e inversión.</p><div className="actions"><Link className="btn primary" href="/grupo">Conocer el grupo</Link><Link className="btn" href="/inversores">Área inversores</Link></div></div>
   <img className="hero-logo" src="/logos/demeter-corp.png" alt="Demeter Corp"/>
  </div></section>
  <section className="section white"><div className="shell"><div className="section-head"><div><span className="eyebrow">NUESTRAS EMPRESAS</span></div><div><h2>Una estructura especializada para identificar y desarrollar oportunidades.</h2><p className="lead">Cada compañía del grupo opera con un enfoque definido, compartiendo una misma cultura de análisis, discreción y creación de valor sostenible.</p></div></div><div className="company-grid">{companies.map(c=><article className="company-card" key={c.name}><div><img src={c.img} alt={c.name}/><h3>{c.name}</h3><span className="eyebrow">{c.sub}</span><p>{c.txt}</p>{c.href && <a className="text-link" href={c.href} target={c.external ? '_blank' : undefined} rel={c.external ? 'noopener noreferrer' : undefined}>Visitar {c.name} ↗</a>}</div><div className={'line '+c.line}></div></article>)}</div></div></section>
  <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">ÁREAS DE ENFOQUE</span></div><div><h2>Sectores donde los activos, el territorio y los recursos se encuentran.</h2></div></div><div className="sector-grid">{sectors.map(s=><div className="sector" key={s[1]}><div className="icon">{s[0]}</div><b>{s[1]}</b><span>{s[2]}</span></div>)}</div></div></section>
  <section className="section dark"><div className="shell"><div className="section-head"><div><span className="eyebrow">PARA INVERSORES</span></div><div><h2>Privacidad, rigor y visión empresarial.</h2><p className="lead">Estudiamos oportunidades con una perspectiva transversal: activo, estructura, riesgos, territorio, ejecución y potencial de creación de valor.</p></div></div><div className="metrics"><div className="metric"><strong>01</strong><span>Identificación de oportunidades</span></div><div className="metric"><strong>02</strong><span>Análisis y estructuración</span></div><div className="metric"><strong>03</strong><span>Desarrollo y ejecución</span></div><div className="metric"><strong>04</strong><span>Seguimiento de largo plazo</span></div></div></div></section>
  <section className="section white"><div className="shell"><div className="section-head"><div><span className="eyebrow">PROYECTOS</span></div><div><h2>Capacidad para trabajar con activos complejos.</h2><p className="lead">La web queda preparada para incorporar proyectos públicos, teasers de inversión y documentación privada para inversores autorizados.</p></div></div></div></section>
 </>
}
