export const metadata={title:'Empresas del grupo — Demeter Corp, Demeter God, Demeter Water Consulting, Demeter Soluciones Estratégicas',description:'Estructura societaria de Grupo Demeter: cuatro sociedades especializadas en gobierno corporativo, patrimonio inmobiliario, consultoría hídrica y grandes contratos estratégicos.'}

const empresas=[
 {id:'demeter-corp',name:'DEMETER CORP',tag:'La cabecera del grupo',logo:'/logos/demeter-corp.png',rol:'Sociedad matriz',areas:['Gobierno corporativo','Estrategia y asignación de capital','Relación con inversores y entidades financieras','Estructuración de sociedades vehículo'],aporta:[['Un único interlocutor','Quien quiere relacionarse con el grupo en su conjunto habla con Demeter Corp, no con cuatro sociedades distintas.'],['Disciplina financiera','Estándares comunes de gestión de riesgos, reporting y gobierno para todas las sociedades operativas.'],['Capital donde rinde','Asigna recursos entre las sociedades según el criterio de inversión del grupo, no según la inercia de cada línea.']],parrafos:[
  'Demeter Corp es la sociedad matriz de Grupo Demeter. No ejecuta proyectos directamente: gobierna, financia y supervisa a las sociedades que sí lo hacen.',
  'Su función es doble. De puertas para adentro, define la estrategia del grupo, asigna capital entre las sociedades operativas según el criterio de inversión del grupo, y supervisa el desempeño de cada una. Establece los estándares de gobierno corporativo, de gestión de riesgos y de reporting que se aplican en todo el grupo, con independencia del sector en el que opere cada sociedad.',
  'De puertas para afuera, Demeter Corp es la contraparte natural de inversores institucionales, entidades financieras y socios que buscan relacionarse con el grupo en su conjunto y no con una sola línea de negocio. Es quien negocia la entrada de capital externo, quien estructura las sociedades vehículo cuando una operación lo requiere, y quien responde, en última instancia, por el conjunto de las decisiones estratégicas del grupo.',
  'Demeter Corp no compite con sus propias sociedades operativas ni les resta autonomía técnica: las coordina. El equipo de Demeter God conoce activos inmobiliarios como nadie en el grupo; el de Demeter Water Consulting entiende de regulación hídrica mejor que cualquier generalista; el de Demeter Soluciones Estratégicas sabe lo que exige un pliego de licitación pública. Demeter Corp no sustituye ese conocimiento: lo pone al servicio de una misma estrategia, con visión de conjunto y disciplina financiera.',
  'Es, en definitiva, el punto de entrada para cualquier conversación que involucre al grupo como un todo: inversión, alianzas estratégicas u operaciones que requieran la capacidad combinada de varias sociedades.',
 ]},
 {id:'demeter-god',name:'DEMETER GOD',tag:'El brazo patrimonial',web:'https://demetergod.com',logo:'/logos/demeter-god.png',rol:'Patrimonio inmobiliario',areas:['Adquisición de activos','Desarrollo y rehabilitación integral','Explotación directa: alojamiento turístico','Activos en renta'],aporta:[['Patrimonio tangible','Activos con valor contable y de mercado propio que generan ingresos recurrentes para el grupo.'],['Control en todas las fases','Sabe qué compró, qué le hizo y cómo se comporta en explotación. Ese conocimiento alimenta cada nueva compra.'],['Vehículo de coinversión','Entrada natural para socios que buscan exposición inmobiliaria y de alojamiento con ejecución propia.']],parrafos:[
  'Demeter God es la sociedad del grupo especializada en activos inmobiliarios: su adquisición, su desarrollo, su rehabilitación y, de forma determinante, su explotación directa una vez incorporados al patrimonio del grupo.',
  'Su ámbito de actuación cubre todo el ciclo del activo inmobiliario. Identifica oportunidades de adquisición —edificios, suelo, activos con potencial de reposicionamiento— y evalúa su viabilidad técnica, urbanística y económica antes de comprometer capital. Cuando el activo lo requiere, gestiona su desarrollo o rehabilitación integral, coordinando el proceso constructivo y administrativo de principio a fin. Y, a diferencia de un promotor que vende al terminar la obra, Demeter God explota directamente una parte relevante de su patrimonio: gestión de alojamiento turístico y de activos en renta, con visión de permanencia, no de rotación rápida.',
  'Esa combinación —adquirir, transformar y después operar— es lo que distingue a Demeter God de un simple inversor inmobiliario o de una gestora de alquiler. La sociedad conserva el conocimiento del activo en todas sus fases: sabe qué compró, sabe qué le hizo, y sabe cómo se comporta una vez en explotación, lo que retroalimenta cada nueva decisión de adquisición.',
  'Dentro del grupo, Demeter God aporta el componente patrimonial tangible: activos con valor contable y de mercado propio, generadores de ingresos recurrentes, que equilibran la actividad de contrato y consultoría de las demás sociedades. Es también, con frecuencia, el vehículo natural para operaciones de coinversión con socios interesados específicamente en el sector inmobiliario y de alojamiento, dentro de un grupo con capacidad de ejecución propia sobre el activo.',
 ]},
 {id:'demeter-water-consulting',name:'DEMETER WATER CONSULTING',tag:'La consultoría del agua',logo:'/logos/demeter-water.png',rol:'Gestión del agua',areas:['Regeneración y reutilización de aguas','Infraestructura hidráulica','Concesiones administrativas','Proyectos de regadío'],aporta:[['Lectura técnica de la norma','Reglamento (UE) 2020/741 y Real Decreto 1085/2024 interpretados por quien los aplica en proyecto, no solo por quien los cita.'],['Proyectos tramitables','Convierte una necesidad hídrica en un expediente viable ante la administración competente.'],['Un recurso escaso, gestionado','Foco en operaciones industriales, agrícolas y administrativas donde el agua es estratégica.']],parrafos:[
  'Demeter Water Consulting es la sociedad del grupo especializada en la gestión del agua no destinada a consumo humano: regeneración, reutilización, infraestructura hidráulica y tramitación de concesiones administrativas vinculadas al recurso.',
  'Su trabajo se sitúa en la intersección entre ingeniería, regulación y gestión de proyecto. Analiza la viabilidad técnica y normativa de operaciones de regeneración y reutilización de aguas, diseña la infraestructura hidráulica asociada, y acompaña a administraciones, empresas y propietarios de activos a través de los procesos de concesión administrativa que este tipo de proyectos exige. También interviene en proyectos vinculados al regadío, donde la disponibilidad y la gestión eficiente del recurso condicionan directamente la viabilidad de la actividad agrícola.',
  'El marco regulatorio en el que opera Demeter Water Consulting es exigente y cambiante: el Reglamento (UE) 2020/741 sobre reutilización del agua y su desarrollo en el Real Decreto 1085/2024 han sustituido el marco anterior, y su correcta interpretación técnica y administrativa es determinante para que un proyecto de reutilización llegue a buen término. Esa lectura precisa de la norma —no solo el conocimiento de la ingeniería— es lo que distingue a una consultoría hídrica seria de una genérica.',
  'Demeter Water Consulting no es consultoría agraria ni gestión de riego doméstico: es consultoría de gestión del agua, con foco en proyectos de escala industrial, agrícola o administrativa donde el recurso hídrico es escaso, regulado y estratégico. Dentro del grupo, aporta el conocimiento técnico y normativo que convierte una necesidad hídrica en un proyecto viable y tramitable.',
 ]},
 {id:'demeter-soluciones-estrategicas',name:'DEMETER SOLUCIONES ESTRATÉGICAS',tag:'Los grandes contratos',logo:'/logos/demeter-soluciones.png',rol:'Energía, infraestructura y tecnología',areas:['Energía y transición energética','Infraestructura','Licitación y contratación pública','Desarrollo de software propio'],aporta:[['Ejecución interna','Capacidad técnica propia para asumir un contrato estratégico de principio a fin, sin subcontratar el núcleo.'],['Acceso al contrato público','Conocimiento del procedimiento administrativo y de la normativa de contratación del sector público.'],['Tecnología que decide','Herramientas desarrolladas en casa para analizar, gestionar y operar mejor cada proyecto del grupo.']],parrafos:[
  'Demeter Soluciones Estratégicas es la sociedad del grupo que asume los contratos de mayor escala y complejidad: energía, infraestructura, licitación pública y desarrollo tecnológico propio.',
  'En energía, su actividad cubre desde proyectos convencionales de generación hasta iniciativas vinculadas a la transición energética, incluido el hidrógeno verde como vector de futuro. En infraestructura, participa en el desarrollo y ejecución de proyectos que requieren capacidad técnica y financiera propia, no solo intermediación. En licitación pública, concurre y ejecuta contratos con administraciones, un terreno que exige tanto capacidad técnica como un conocimiento profundo del procedimiento administrativo y de la normativa de contratación del sector público. Y en tecnología, desarrolla software propio: herramientas internas de análisis y gestión que el grupo utiliza para tomar mejores decisiones de inversión y de operación.',
  'Lo que une estas cuatro líneas de actividad, aparentemente distintas, es el tipo de operación que Demeter Soluciones Estratégicas está diseñada para asumir: proyectos de mayor envergadura, plazos más largos, procedimientos administrativos más exigentes y una necesidad real de capacidad de ejecución técnica interna, no subcontratada.',
  'Dentro del grupo, es la sociedad que permite a Demeter competir por operaciones de mayor tamaño sin depender de terceros para la parte técnica o tecnológica. Es, con frecuencia, la contraparte natural de administraciones públicas y de socios industriales que buscan un ejecutor capaz de asumir un contrato estratégico de principio a fin.',
 ]},
]

import HeroArt from '../../components/HeroArt'

export default function Empresas(){return <>
 <section className="page-hero"><div className="shell page-hero-grid"><div><span className="eyebrow">EMPRESAS DEL GRUPO</span><h1>Cuatro sociedades. Una misma matriz. Ningún riesgo compartido por defecto.</h1><p>Grupo Demeter no opera como una empresa única que abarca todo. Opera como una estructura en holding, con Demeter Corp como cabecera y tres sociedades especializadas bajo su gobierno.</p></div><div className="page-hero-art"><HeroArt kind="diamond" accent="#c7a25b"/></div></div></section>

 <section className="section white" style={{paddingBottom:0}}><div className="shell"><div className="section-head"><div><span className="eyebrow">ESTRUCTURA</span></div><div><h2>Así se organiza el grupo.</h2><p className="lead">Una matriz que gobierna y tres sociedades operativas que ejecutan, cada una en su sector.</p></div></div>
  <div className="org-chart">
   <a className="org-node parent" href="#demeter-corp"><img src="/logos/demeter-corp.png" alt="Demeter Corp"/><b>Demeter Corp</b><span>Sociedad matriz</span></a>
   <div className="org-connector" aria-hidden="true"><i/><i/></div>
   <div className="org-children">{empresas.filter(e=>e.id!=='demeter-corp').map(e=><a className="org-node" href={'#'+e.id} key={e.id}><img src={e.logo} alt={e.name}/><b>{e.name.split(' ').map(w=>w.charAt(0)+w.slice(1).toLowerCase()).join(' ')}</b><span>{e.rol}</span></a>)}</div>
  </div>
 </div></section>

 <section className="section white"><div className="shell content-grid"><div><span className="eyebrow">POR QUÉ EL HOLDING</span></div><div className="copy">
  <p>Cada sociedad asume su propio riesgo. Un proyecto de infraestructura energética no compromete el patrimonio inmobiliario del grupo, ni una operación de desarrollo urbanístico expone la actividad de consultoría hídrica. Esa separación permite entrar en operaciones de mayor riesgo técnico o administrativo sin trasladar esa exposición al resto del grupo.</p>
  <p>Cada sociedad, además, se especializa de verdad: equipos, procesos y relaciones institucionales propias de su sector, en lugar de un equipo generalista que reparte su atención entre materias distintas.</p>
  <p>Y cuando una operación lo exige, el grupo puede integrar una operación completa —originación, ejecución técnica, financiación, gestión patrimonial— combinando la capacidad de varias sociedades bajo una misma dirección estratégica. Esa es la ventaja de la estructura: especialización sin fragmentación.</p>
 </div></div></section>

 {empresas.map((e,i)=><section className={'section '+(i%2===0?'':'white')} id={e.id} key={e.id}><div className="shell content-grid company-profile">
  <aside className="company-side">
   <div className="company-logo"><img src={e.logo} alt={e.name}/></div>
   <span className="eyebrow">{e.name}</span>
   <p className="company-role">{e.rol}</p>
   <b className="company-side-title">Áreas de actividad</b>
   <ul className="company-areas">{e.areas.map(a=><li key={a}>{a}</li>)}</ul>
   {e.web && <a className="btn small outline-dark" href={e.web} target="_blank" rel="noopener noreferrer">Visitar demetergod.com ↗</a>}
  </aside>
  <div className="copy">
   <h2>{e.tag}</h2>
   {e.parrafos.map((p,j)=><p key={j}>{p}</p>)}
   <div className="company-value"><span className="eyebrow">QUÉ APORTA AL GRUPO</span><div className="company-value-grid">{e.aporta.map(v=><div key={v[0]}><b>{v[0]}</b><p>{v[1]}</p></div>)}</div></div>
  </div>
 </div></section>)}
</>}
