import Link from 'next/link'

export const metadata={title:'Demeter Water Consulting | Demeter Corp',description:'Consultoría, ingeniería y gestión de proyectos de agua no destinada a consumo humano.'}

export default function DemeterWaterConsulting(){
 const areas=[['Consultoría','Análisis de viabilidad técnica, normativa y económica de proyectos vinculados al agua.'],['Ingeniería','Diseño y desarrollo técnico de infraestructuras y soluciones hídricas.'],['Gestión de proyectos','Coordinación integral del proyecto, desde su concepción hasta su puesta en marcha.']]
 const steps=[['01','Diagnóstico','Análisis del recurso disponible, el marco normativo aplicable y las necesidades reales del proyecto.'],['02','Diseño','Definición técnica de la solución y de la ingeniería asociada al proyecto.'],['03','Tramitación','Acompañamiento en autorizaciones, concesiones y trámites administrativos necesarios.'],['04','Ejecución y seguimiento','Gestión del proyecto hasta su puesta en marcha, con seguimiento posterior.']]
 return <>
  <section className="page-hero"><div className="shell"><Link className="back-link" href="/empresas">← Empresas del grupo</Link><span className="eyebrow">DEMETER WATER CONSULTING</span><h1>Consultoría e ingeniería para proyectos de agua.</h1><p>Sociedad del grupo especializada en consultoría, ingeniería y gestión de proyectos vinculados al agua no destinada a consumo humano.</p></div></section>
  <section className="section white"><div className="shell content-grid"><div><span className="eyebrow">LA COMPAÑÍA</span></div><div className="copy"><h2>Un recurso que exige criterio técnico y rigor normativo.</h2><p>El agua no destinada a consumo humano —riego agrícola, uso industrial, regeneración ambiental o procesos productivos— plantea retos técnicos, normativos y de gestión que requieren conocimiento especializado. Demeter Water Consulting acompaña a administraciones, empresas y propietarios de activos a lo largo de todas las fases de estos proyectos.</p><p>El trabajo combina ingeniería, conocimiento del marco concesional y administrativo, y capacidad de gestión de proyecto de principio a fin, con el mismo rigor y la misma visión de largo plazo que caracteriza al resto del grupo.</p><div className="values">{areas.map(a=><div className="value" key={a[0]}><h3>{a[0]}</h3><p>{a[1]}</p></div>)}</div></div></div></section>
  <section className="section dark"><div className="shell investor-panel"><div><span className="eyebrow">CÓMO TRABAJAMOS</span><h2>De la necesidad al proyecto en marcha.</h2><p className="lead">Cada proyecto se aborda con el mismo proceso ordenado, adaptado a la escala y complejidad del recurso hídrico implicado.</p><div className="actions"><Link className="btn primary" href="/contacto">Hablar con el equipo</Link></div></div><div className="investor-list">{steps.map(s=><div className="investor-item" key={s[0]}><b>{s[0]} · {s[1]}</b><span>{s[2]}</span></div>)}</div></div></section>
 </>
}
