import Link from 'next/link'

export const metadata={title:'Demeter Soluciones Estratégicas | Demeter Corp',description:'Intermediación y estructuración de activos de energía, agricultura y activos estratégicos.'}

export default function DemeterSolucionesEstrategicas(){
 const areas=[['Energía','Intermediación de plantas fotovoltaicas, activos de generación y oportunidades vinculadas a la transición energética.'],['Agricultura','Fincas, suelo productivo y activos agrícolas con potencial de explotación o desarrollo.'],['Activos estratégicos','Identificación e intermediación de activos de terceros con una lógica económica y operativa clara.']]
 const steps=[['01','Identificación','Localización de activos con fundamento técnico y económico, propios o de terceros.'],['02','Verificación','Revisión documental, administrativa y de la situación real del activo antes de plantear cualquier operación.'],['03','Intermediación','Puesta en contacto con compradores o inversores cualificados, con la información necesaria para decidir.'],['04','Cierre','Acompañamiento hasta la formalización de la operación, con discreción y criterio profesional.']]
 return <>
  <section className="page-hero"><div className="shell"><Link className="back-link" href="/empresas">← Empresas del grupo</Link><span className="eyebrow">DEMETER SOLUCIONES ESTRATÉGICAS</span><h1>Intermediación y estructuración de activos estratégicos.</h1><p>Sociedad del grupo especializada en identificar, intermediar y poner en valor activos de terceros vinculados a la energía, la agricultura y otros activos con fundamento económico.</p></div></section>
  <section className="section white"><div className="shell content-grid"><div><span className="eyebrow">LA COMPAÑÍA</span></div><div className="copy"><h2>Del activo disponible a la operación cerrada.</h2><p>Demeter Soluciones Estratégicas actúa como intermediario especializado entre propietarios de activos y compradores o inversores cualificados. Su trabajo combina conocimiento técnico del activo, criterio de mercado y capacidad para estructurar operaciones con seriedad y discreción.</p><p>La sociedad trabaja principalmente con activos de terceros: plantas fotovoltaicas en distintas fases de desarrollo o explotación, activos energéticos vinculados a la transición energética, y fincas y suelo productivo del sector agrícola. En todos los casos, el punto de partida es el mismo: entender el activo —su situación administrativa, técnica y económica— antes de plantear cualquier operación.</p><div className="values">{areas.map(a=><div className="value" key={a[0]}><h3>{a[0]}</h3><p>{a[1]}</p></div>)}</div></div></div></section>
  <section className="section dark"><div className="shell investor-panel"><div><span className="eyebrow">CÓMO TRABAJAMOS</span><h2>Rigor en cada fase de la operación.</h2><p className="lead">Cada intermediación sigue un proceso ordenado, desde la identificación del activo hasta el cierre de la operación con la contraparte adecuada.</p><div className="actions"><Link className="btn primary" href="/contacto">Hablar con el equipo</Link></div></div><div className="investor-list">{steps.map(s=><div className="investor-item" key={s[0]}><b>{s[0]} · {s[1]}</b><span>{s[2]}</span></div>)}</div></div></section>
 </>
}
